### ISSUE TITLE
NEED HELP WITH VOICE

### ISSUE THREAD

**Issue by lilkid3** [kyzmitch/resiprocate-swift-demo#1]
Good Day, I was wondering if you have found a way to use media with resiprocate, because i have been looking for a media stack to use with resiprocate. Thanks

**Comment by kyzmitch** [comment]
Hi, no, it was just an attempt to use it in Swift project

**Comment by lilkid3** [comment]
> Hi, no, it was just an attempt to use it in Swift project

Ok. Thanks
